FROM node:18

WORKDIR /usr/src/app
#Copy both package-lock.json and package.json files and install dependencies
COPY package*.json ./
RUN npm install
#Copy app files and build
COPY . .
RUN npm run build
# Start the server
CMD [ "node", "dist/main.js" ]